NewsItem:
  fields:
    default: headline, summary, content
    list: headline, summary, content
    form: headline, summary, content
  filters: headline
  search: headline, summary, content
  application: nal
  description: News Administration