Asset:
  fields:
    default: name, asset, thumb, asset_file_name, asset_file_size
    list: name, asset,  thumb, asset_file_name, asset_file_size
    form: name, asset, thumb, description
  filters: name
  search: name, description
  application: Assets
  description: Site Assets