NewsItem:
  fields:
    default: headline, summary, content
#    list: headline, summary, created_at
    list: headline, summary, created_at
    form: headline, summary, content, created_at
  filters:
  relationships: assets
  search: headline, summary, content
  application: News
  description: News Admin