Page:
  fields:
    default: name, slug, year
    list: name, slug, year
    form: name, slug, year
  filters: year
  relationships: content_areas
  search: name, slug
  application: Pages
  description: Pages Admin