Page:
  fields:
    default: name, slug, year
    list: name, slug, year,  created_at
    form: name, slug, year, content
  filters: year
  relationships: content_areas, assets
  search: name, slug, content
  application: Pages
  description: Pages Admin