Page:
  fields:
    default: name, slug, year, section
    list: name, slug, year,  created_at, section
    form: name, slug, year, content, section
  filters: year, section
  relationships: content_areas, assets
  search: name, slug, content
  application: Pages
  description: Pages Admin