Performer:
  fields:
    default: name, biography, homepage, twitter_name
    list: name, biography, homepage, twitter_name
    form: name, biography, homepage, twitter_name
  filters: name
  relationships:
  search: name, biography, homepage, twitter_name
  application: Participants
  description: Artist/Performers/Speakers Admin

Artist:
  fields:
    default: name, biography, homepage, twitter_name
    list: name, biography, homepage, twitter_name
    form: name, biography, homepage, twitter_name
  filters: name
  relationships:
  search: name, biography, homepage, twitter_name
  application: Participants
  description: Artist/Performers/Speakers Admin

Speaker:
  fields:
    default: name, biography, homepage, twitter_name
    list: name, biography, homepage, twitter_name
    form: name, biography, homepage, twitter_name
  filters: name
  relationships:
  search: name, biography, homepage, twitter_name
  application: Participants
  description: Artist/Performers/Speakers Admin