Performer:
  fields:
    default: name, biography, homepage, twitter_name, year
    list: name, biography, homepage, twitter_name, year
    form: name, biography, homepage, twitter_name, year
  filters: name, year
  relationships:
  search: name, biography, homepage, twitter_name, year
  application: Participants
  description: Artist/Performers/Speakers Admin

Artist:
  fields:
    default: name, biography, homepage, twitter_name, year
    list: name, biography, homepage, twitter_name, year
    form: name, biography, homepage, twitter_name, year
  filters: name, year
  relationships:
  search: name, biography, homepage, twitter_name, year
  application: Participants
  description: Artist/Performers/Speakers Admin

Speaker:
  fields:
    default: name, biography, homepage, twitter_name, year
    list: name, biography, homepage, twitter_name, year
    form: name, biography, homepage, twitter_name, year
  filters: name, year
  relationships:
  search: name, biography, homepage, twitter_name, year
  application: Participants
  description: Artist/Performers/Speakers Admin