development:
  access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] || "dummy_key" %>
  secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] || "dummy_secret" %>
  url: "nal.s3.amazonaws.com"
test:
  access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] || "dummy_key" %>
  secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] || "dummy_secret" %>
  url: "nal.s3.amazonaws.com"
production:
  access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] || "dummy_key" %>
  secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] || "dummy_secret" %>
  url: "nal.s3.amazonaws.com"


#'nal.s3-website-eu-west-1.amazonaws.com